---
keyservers:
  - url: "hkps://keyserver.ubuntu.com"
    name: "ubuntu"
  - url: "hkps://keyserver.dcc.sib.swiss"
    name: "swiss"
  - url: "hkps://keys.openpgp.org"
    name: "openpgp"
  - url: "hkps://pgp.mit.edu"
    name: "mit"
ringdir: "/home/dfoulks/Projects/gpgremlin/keyrings"
min_key: 4096
